from brainrender import Scene
from brainrender.actors import Point
import matplotlib
import pickle
import numpy as np
from pathlib import Path

# https://stackoverflow.com/questions/25408393/getting-individual-colors-from-a-color-map-in-matplotlib
# 13200 µm x 8000 µm x 11400 µm

# alternatively https://github.com/brainglobe/brainrender-docs/blob/master/autogenerated-docs/brainrender-autodocs/colors.md

cmap = matplotlib.cm.get_cmap('Spectral')

rgba = cmap(0.5)

path = Path.home() / 'Desktop' / 'data' / 'connectivity'

filename = path / 'ipsilateral_centroids_dict_hem_1_VISam.pkl'
with open(filename, 'rb') as f: ipsilateral_centroids_dict = pickle.load(f)

# xyz = np.array([[area]])
vals = ipsilateral_centroids_dict.values()
xyz = [area[:3] for area in vals]
proj_metric = [area[3] for area in vals]

norm = matplotlib.colors.Normalize(vmin=min(proj_metric), vmax=max(proj_metric))

# Create a brainrender scene
scene = Scene(title="brain regions")

# Add brain regions
# scene.add_brain_region("TH")

# You can specify color, transparency...
# scene.add_brain_region("MOs", "CA1", alpha=0.2, color="green")
scene.add_brain_region("VISam", "VISpm", "RSPagl", alpha=0.2, color="green")
scene.add_brain_region("VISp", alpha=0.2, color="red")

# for i in range(len(xyz)):
#     c = matplotlib.colors.rgb2hex(cmap(norm(proj_metric[i])))
#     scene.add(Point(xyz[i], name="Cells", color=c))

# Render!
scene.render()